### ISSUE TITLE
Postitada esimene administraatorite/moderaatorite läbipaistvusraport

### ISSUE THREAD

**Issue by boamaod** [est-social/est-social.github.io#11]
Võiks postitada, et mida me seni ja miks vaigistanud ja blokkinud oleme, missuguseid intsidente lahendama pidanud. See annaks aimu meie tegevusest ja oleks teatud mõttes ka juhis kasutajatele.

Edaspidi võiks seda teha teatud regulaarsusega.

**Comment by markokivimaepriv** [comment]
https://est.social/@marko/109714953251744625 - esimene raport.

Kas seda korrata või teha regulaarseks - eks näis. Hetkel on olnud vaja nii vähe modereerida, et regulaarsust ei plaani. Küll aeg annab arutust.

**Comment by jaanus** [comment]
Üks raport tehtud, seega miinimumeesmärk täidetud.

Edaspidi on variant ka teha neid blogipostitustena vms, kui tegevus laieneb ja materjali rohkem. Mastodoni-postitus hetkel käib küll.
