### ISSUE TITLE
Modereerimisjuhise koostamine

### ISSUE THREAD

**Issue by boamaod** [est-social/est-social.github.io#22]
Seni oleme kujundanud modereerimispraktikat moderaatorite jututoas ja mujal vestlustes, reeglite mustandit toimetades ja kahel videokoosolekul, millest ühel kinnitasime [esialgsed reeglid](https://kogukond.est.social/docs/reeglid/). Reeglite rakendamisel selgub pidevalt uusi nüansse ja nende põhjal peaks kirja panema mingitlaadi modereerimispõhimõtete dokumendi, mis annaks kogemust edasi nt uutele moderaatoritele, kui need liituvad tiimiga, aga oleks ka enesekontrolliks praegusele tiimile.

Põhimõtteliselt võib vajalikku infot ilmselt lisada siia pileti alla, ka puutub siia pilet #11.

**Comment by boamaod** [comment]
Siin on [ingliskeelne dokumentatsioon](https://docs.joinmastodon.org/admin/moderation/), mis katab osa modereerimisliidesest  (vt ka [kasutajapoolse liidese dokumentatsioon](https://docs.joinmastodon.org/user/moderating/)).

**Comment by markokivimaepriv** [comment]
See mustand on üsna okei, MVP on olemas.
