### ISSUE TITLE
Poliitreklaam, propaganda, tundlik sisu ja soovituslikud räsimärgid/teemaviited

### ISSUE THREAD

**Issue by boamaod** [est-social/est-social.github.io#23]
Siin oleks vaja veidi sõeluda olemasolevaid praktikaid ja vaadata üle [reeglite seletuses](https://kogukond.est.social/docs/reeglite-seletus/) antud esialgsed soovitused, mh pidades silmas kandideerimishooaja algust, mis avati meil ametlikult [vist selle postitusega](https://est.social/@jgj/109547761832787588).

Veidi segane on, missuguseid teemaviiteid peaks kasutama koos või eraldi, kas leppida kokku eestikeelsed või rahvusvahelised või eristada need selgelt ja kas peaks olema mingi veidi peenem `CW` loend/juhis, mis vastaks paremini kasutajate vajadustele. Ka võiks midagi ütelda selle kohta, millal oleks kena oma postitused või botid avalikust voost ära korjata (esialgu on see moderaatorite sisetundest ja kokkuleppest lähtuv).

Neil teemadel võiks kasutajatelt püüda veel tagasisidet saada.

**Comment by markokivimaepriv** [comment]
Pole paha mõte, võiks tegeleda siis, kui on mure käes. Raske kuival maal ujuma õppida.
