### ISSUE TITLE
Isikutuvastus ja paroodiakontode staatus

### ISSUE THREAD

**Issue by boamaod** [est-social/est-social.github.io#26]
Vajaks lahti kirjutamist reeglites ja modereerimisreeglites? Peamised küsimused:

* Millal peame vajalikuks tuvastada?
   * Tuntud isikute puhul
   * Segase motivatsiooniga kontode puhul
* Kui on kahtlus, mis protsessi järgime?
* Millal on paroodiakontod lubatud ja kes vastutab?
* Kas on mingi vaikimisi protsess, millega saab kõiki probleeme vältida konto registreerimisel?
* Kas lisame reeglitesse midagi või on see moderaatorite eneseregulatsiooni asi?

**Comment by markokivimaepriv** [comment]
Selle võiks lahendada kasutaja ID-kaardi või muu sarnase tokeniga autentimine.
