### ISSUE TITLE
Puudub raporteerimisjuhis

### ISSUE THREAD

**Issue by boamaod** [est-social/est-social.github.io#3]
Seda on mõistlik omada ilmselt eraldi dokumendina, aga panna üldkirjeldusse lühike lahtikirjutus ja link sellele dokumendile. Lisaks sellele võiks raporteerimisjuhis sisaldada juhiseid häireolukorra kohta, st kui raporteerimisest ei piisa ja tuleks pöörduda nt eluliini, politsei vmt pädeva institutsiooni poole. See joonib ühtlasi alla, mis piirides moderaatorid vastutuse võtavad ja tegelikult näitab, et seda tehakse tõsiselt (ei püüta modereerimisega lahendada probleeme, mida see ei saa lahendada).

**Comment by boamaod** [comment]
Raporteerimisjuhis on nüüd [reeglite lahtiseletuse üldosas](https://abi.est.social/docs/reeglite-seletus/). Selle võiks lisada lühidalt ka serveri [kirjeldavasse teksti](https://github.com/est-social/est-social.github.io/blob/main/drafts/serveri-kirjeldus.md), siis võib selle töö esialgsel kujul tehtuks lugeda.

**Comment by markokivimaepriv** [comment]
Ma lähtuks tervest mõistusest hetkel - juhtumeid on vähe, raporteerimine toimib intuitiivselt. Seda pole vaja ära reguleerida.
