### ISSUE TITLE
Abimaterjalide raamistamine

### ISSUE THREAD

**Issue by boamaod** [est-social/est-social.github.io#5]
Vaatasin, et üks silmapaistev Mastodoni isend [avas just](https://community.hachyderm.io/docs/) meiega sarnase juhendmaterjalide saidi ja nimetas selle "kogukonnasaidiks". Äkki peaks seda eeskuju järgima, et olla kaasavam -- abiliin loob väga vertikaalse kuvandi.

**Comment by jaanus** [comment]
Üks (küll rohkem tehnilistele kasutajatele suunatud) Mastodon pani enda meta-saidi nimeks meta. Kah variant. https://meta.chaos.social/

**Comment by boamaod** [comment]
Saan aru, et subkultuuris on kasutusel ka `CW` marker `meta`, millega saavad kasutajad Mastodoni reeglite jm politiiliste küsimuste arutamisest hoiduda.

**Comment by boamaod** [comment]
@markokivimaepriv arvas, et `kogukond.est.social` sobiks. Minu meelest sobib `tugi.est.social` ka. Mõlema puhul läheks saidi pealkirja midagi kogukonnast ja/või abimaterjalidest, st alamdomeen lihtsalt joonib alla mingit külge. Minu meelest 'kogukond' on isegi parem, aga lihtsalt pikem. Lasen veel veidi settida ja kui muid mõtteid ei tule, siis teen sammud, et kolida kogukonna alla -- siis on selge, et seda koostatakse üheskoos ja teadete sektsiooni olemasolu on ka loogilisem.
