### ISSUE TITLE
Est.sociali veebiotsingute seadistamine

### ISSUE THREAD

**Issue by boamaod** [est-social/est-social.github.io#7]
Est.social ja abi.est.social tuleks seadistada nii, et [Google](https://search.google.com/search-console/about) ja teised neid korrektselt indekseeriks. Kasutajatele võiks otsingu tulemusel kuvada loogilsi alamlehti.

**Comment by SlyEcho** [comment]
Vaatan

**Comment by SlyEcho** [comment]
Nüüd peaks olema Search Console'is ja jagatud kõikidega.

**Comment by boamaod** [comment]
Peaks samamoodi lisama ka abi.est.social alamdomeeni.

**Comment by SlyEcho** [comment]
Nüüd on vist.

**Comment by boamaod** [comment]
Kui omanikukontroll ka läbi teha, siis võib pileti kinni panna vist. Ehk:

* [est.social](https://search.google.com/search-console/ownership?resource_id=sc-domain%3Aest.social)
* [abi.est.social](https://search.google.com/search-console/ownership?resource_id=sc-domain%3Aabi.est.social)

Siis peaks saama otsinguparameetreid ja tulemuste näitamist ka veidi seadistada Google'i jaoks. Sama saab muidugi teha ka teiste otsimootoritega nagu Bing, Yandex.
