### ISSUE TITLE
Zone SMTP serveri seadistus

### ISSUE THREAD

**Issue by SlyEcho** [est-social/est-social.github.io#8]
## Probleem
Praegu on kasutusel [SparkPost EU](p.eu.sparkpost.com/) meilisaatja.
See on tasuline praegu (20$ kuus), sest meilikogus on liiga suur tasuta kasutustaseme jaoks.

## Lahendus
Zone on meile andnud ka VPSi kus on meilisaatmise võimalus.
Tuleb seadistada `.env.production` failis õigesti.

Info zone-st:
- [Kirjade saatmine veebiserverist](https://help.zone.eu/kb/kirjade-saatmine-veebiserverist/)
- [E-posti seadistamine](https://help.zone.eu/kb-categories/e-posti-seadistamine/)

**Comment by SlyEcho** [comment]
[Kirjade saatmine veebiserverist](https://help.zone.eu/kb/kirjade-saatmine-veebiserverist/) ütleb, et kirje saab saata ainult virtuaalserveri siseselt localhosti peale.

Ütleb ka, et kirjade saatmisel on range piirang 1 kiri iga 5 sekundi järelt.

Ma ei tea, kuidas seda lahendada. Kas on võimalik sinna installida mingi programm vahele, mis kirju edasi saadab?

**Comment by jaanus** [comment]
SMTP käib tänasest Zone serveri kaudu.
