### ISSUE TITLE
Reeglite keelemääratlus on segane

### ISSUE THREAD

**Issue by boamaod** [est-social/est-social.github.io#9]
Praegu ei ole selge, kas eesti keel on nõutud:

* "Kasuta siin peamiselt eesti keelt, postitamisel määra võimalusel keel."

See jätab segaseks, kas muud keeled on üldse lubatud. Üks võimalus seda lugeda on, et kasuta eesti keelt ja muude keelte kasutamisel määra keel. Aga võib ka lugeda, et lubatud on ikkgi ainult eesti keel ja see tuleks ka alati määrata. Seda [valemuljet](https://mstdn.social/@tramm/109466338879999706) tuleks vähendada selgitavates tekstides, aga võimlik, et ka reeglites?

**Comment by jaanus** [comment]
[Reeglite lahtikirjutus](https://abi.est.social/docs/reeglite-seletus/) oleks hea koht selle lahti kirjutamiseks.

**Comment by boamaod** [comment]
Lahtikirjutuse [esimeses lähenduses](https://github.com/est-social/est-social.github.io/issues/2) on selgitused olemas. Kui saavad avaldatud, siis sulgen selle siin.
